[toolchain]
channel = "nightly-2024-01-15"
components = ["rustfmt", "clippy", "llvm-tools-preview", "rust-src"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
profile = "minimal"
