[build]
rustflags = ["-C", "target-cpu=native"]
target-dir = "target"
incremental = false

[alias]
bench-all = "bench --features benchmarking --all-targets"
release-prod = "build --profile production --features production"
check-latency = "run --release --bin latency_tester"
